name: Update YouTube Playlist

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Setup Chrome and Cookies
        uses: browser-actions/setup-chrome@latest
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests yt-dlp browser-cookie3
          
      - name: Execute Script with Cookies
        run: |
          chmod +x autorun.sh
          echo "Creating cookies.txt file..."
          python -c "
          import browser_cookie3
          import http.cookiejar
          cookies = browser_cookie3.chrome(domain_name='.youtube.com')
          cookie_jar = http.cookiejar.MozillaCookieJar('cookies.txt')
          for cookie in cookies:
              cookie_jar.set_cookie(cookie)
          cookie_jar.save()
          "
          ./autorun.sh
          
      - name: Update Playlist
        run: |
          if [ -f "youtube.m3u" ]; then
            cp youtube.m3u playlist.m3u
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add youtube.m3u playlist.m3u
            git commit -m "Update playlist $(date +%Y-%m-%d_%H-%M-%S)"
            git push
          fi
