name: Update YouTube Playlist

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests yt-dlp
          
      - name: Setup cookies
        run: |
          echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt
          
      - name: Execute Script
        run: |
          chmod +x autorun.sh
          YDL_OPTS='--cookies cookies.txt' ./autorun.sh
        env:
          PYTHONWARNINGS: "ignore"
          
      - name: Update Playlist
        run: |
          if [ -f "youtube.m3u" ]; then
            cp youtube.m3u playlist.m3u
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add -f youtube.m3u playlist.m3u
            git commit -m "Update playlist $(date +%Y-%m-%d_%H-%M-%S)" || true
            git push || true
          fi
