name: Update YouTube Playlist

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Debug Environment
        run: |
          echo "=== Current Directory Structure ==="
          pwd
          ls -la
          echo ""
          echo "=== Repository Contents ==="
          find . -type f -name "*.*"
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests yt-dlp
          
      - name: Check Script Content
        run: |
          echo "=== Content of autorun.sh ==="
          cat autorun.sh || echo "autorun.sh not found"
          echo ""
          echo "=== Content of youtube_channel_info.txt ==="
          cat youtube_channel_info.txt || echo "youtube_channel_info.txt not found"
          
      - name: Execute Script
        run: |
          if [ -f "autorun.sh" ]; then
            chmod +x autorun.sh
            ./autorun.sh
            echo "=== Directory after script execution ==="
            ls -la
          else
            echo "autorun.sh not found"
          fi
          
      - name: Check Generated Files
        run: |
          echo "=== Looking for youtube.m3u ==="
          find . -name "youtube.m3u" || echo "No youtube.m3u found"
          if [ -f "youtube.m3u" ]; then
            echo "=== Content of youtube.m3u ==="
            cat youtube.m3u
          fi
          
      - name: Update Playlist
        if: always()
        run: |
          if [ -f "youtube.m3u" ]; then
            cp youtube.m3u playlist.m3u
            echo "=== Final playlist.m3u content ==="
            cat playlist.m3u
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add -f playlist.m3u
            git commit -m "Update playlist $(date +%Y-%m-%d_%H-%M-%S)"
            git push
          else
            echo "Error: No youtube.m3u file to copy"
          fi
