name: Update YouTube Playlist

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Check Critical Files
        run: |
          echo "=== Content of autorun.sh ==="
          cat autorun.sh
          echo -e "\n=== Content of youtube_channel_info.txt ==="
          cat youtube_channel_info.txt
          echo -e "\n=== Content of youtube.m3u ==="
          cat youtube.m3u
          echo -e "\n=== Content of playlist.m3u ==="
          cat playlist.m3u
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests yt-dlp
          
      - name: Execute Script
        run: |
          chmod +x autorun.sh
          ./autorun.sh
          
      - name: Update Playlist
        run: |
          if [ -f "youtube.m3u" ]; then
            cp youtube.m3u playlist.m3u
            echo "=== Updated playlist.m3u content ==="
            cat playlist.m3u
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add -f playlist.m3u
            git commit -m "Update playlist $(date +%Y-%m-%d_%H-%M-%S)"
            git push
          else
            echo "Error: No youtube.m3u file to copy"
          fi
