name: Update YouTube Playlist

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests yt-dlp
          
      - name: Setup and run
        run: |
          cd YouTubePlaylist
          cp ../youtube_channel_info.txt .
          chmod +x autorun.sh
          ./autorun.sh
          cat youtube.m3u
          
      - name: Copy and check playlist
        run: |
          cp YouTubePlaylist/youtube.m3u ./playlist.m3u
          echo "Content of playlist.m3u:"
          cat playlist.m3u
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f playlist.m3u
          git commit -m "Update playlist" || exit 0
          git push
