name: Update YouTube Playlist

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests yt-dlp
          
      - name: Check files and permissions
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Content of youtube_channel_info.txt:"
          cat youtube_channel_info.txt
          echo "Checking autorun.sh:"
          ls -l autorun.sh
          
      - name: Setup and run
        run: |
          chmod +x autorun.sh
          ./autorun.sh
          echo "Generated playlist content:"
          cat youtube.m3u || echo "youtube.m3u not created"
          
      - name: Copy and check playlist
        run: |
          if [ -f "youtube.m3u" ]; then
            cp youtube.m3u playlist.m3u
            echo "Content of playlist.m3u:"
            cat playlist.m3u
          else
            echo "Error: youtube.m3u not found"
          fi
          
      - name: Commit changes
        run: |
          if [ -f "playlist.m3u" ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add -f playlist.m3u
            git commit -m "Update playlist" || echo "No changes to commit"
            git push
          else
            echo "Error: playlist.m3u not found"
          fi
