name: Update YouTube Playlist

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests yt-dlp
          
      - name: Check Python Script
        run: |
          echo "=== Content of scripts/youtube_m3ugrabber.py ==="
          cat scripts/youtube_m3ugrabber.py
          
      - name: Execute Script with Debug
        run: |
          chmod +x autorun.sh
          echo "=== Current Directory ==="
          pwd
          echo "=== Directory Contents ==="
          ls -la
          echo "=== Scripts Directory Contents ==="
          ls -la scripts/
          echo "=== Running autorun.sh ==="
          ./autorun.sh
          echo "=== After Script Execution ==="
          ls -la
          echo "=== Content of youtube.m3u ==="
          cat youtube.m3u
          
      - name: Update Playlist
        run: |
          if [ -f "youtube.m3u" ]; then
            cp youtube.m3u playlist.m3u
            echo "=== Updated playlist.m3u content ==="
            cat playlist.m3u
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add youtube.m3u playlist.m3u
            git commit -m "Update playlist $(date +%Y-%m-%d_%H-%M-%S)"
            git push
          else
            echo "Error: No youtube.m3u file to copy"
          fi
